baseurl: '/hfd'
name: "Haris Family Dentistry" 
title: "Haris Family Dentistry"
permalink: /:title/
collections:
  knowledge:
    permalink: /knowledge/:title/
    published: true
    page: knowledge
