baseurl: '/hfd'
name: "Haris Family Dentistry" 
title: "Haris Family Dentistry"
permalink: /:title/
collections:
  knowledge:
    output: true
    permalink: /:collection/:title/
    published: true
    page: knowledge
